title: Lin Chen's Homepage
page-top-title: Lin Chen
top-section-bg-text: Blockchain Technology
home-subtitle: Lin Chen&ensp;|&ensp;陈林
copyright-text: '&copy; Lin Chen 2024-2025. All Rights Reserved.'
